### ISSUE TITLE
Adaptation to Pale Moon

### ISSUE THREAD

**Issue by graciecat** [sergi/tabgrenade#45]
I would like to use this excellent add-on in [Pale Moon](http://www.palemoon.org/technical.shtml) browser, a fork of Firefox with [significant differences](http://www.palemoon.org/technical.shtml#Firefox_Differences). Would you be interested in porting your addon over to be Pale Moon compatible?

Although PM does not support Mozilla Add-on SDK, there is [PMKit](http://developer.palemoon.org/Add-ons:Extensions/Jetpack) for adapting JetPack extensions (basically, a library that provides basic compatibility layer with Mozilla Add-on SDK).

Many developers have successfully adapted their JetPack extensions for PM, as you can see here: https://github.com/JustOff/pm27-sdk-addons/blob/master/README.md

**Comment by sergi** [comment]
Hi @graciecat, I'm not interested in adapting the addon myself, but feel free to try by yourself!
